name: webdriverio-ja

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '10 3 * * *'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js LTS
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Lint with eslint
      run: npm run lint
    - name: Test with wdio
      run: npm run test
